In [9]:
# descriptor < encapsulation을 강화하는 방법
# 만드는 방법 3가지가 있다
class A:
    __x = 1 # 맹글링돼서 이름이 바뀜


In [12]:
A._A__x # 외부에서도 접근 가능함

1

In [13]:
class A:
    __x = 1 

    @property # decorator의 종류 중 하나 > method를 변수처럼 사용하게 만들어준다.
              # 실제 변수를 숨길 수 있다 (information hiding encapsulation)
    def tt(self):
        return 1

In [14]:
a = A()

In [19]:
print(a.tt) # @property는 ()를 붙혀야하는 것을 () 붙히지 않게함.
            # @ callable인 얘를 callable이 아닌 것처럼 만듬
            # 즉, 변수처럼 보이게 함.
a.tt()

1


TypeError: 'int' object is not callable

In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3])

In [22]:
a.shape # @property를 정의하면 method라도 ()를 생략할 수 있다.
        # => 변수처럼 보이지만, 변수가 아닐 수도 있다.

(3,)

In [34]:
class A:
    __x = 1 

    @property # decorator
    def tt(self):
        return A.__x # 외부에서는 __x 앞에 _A가 붙어야한다
                     # 하지만 내부에서는 접근이 된다.

In [35]:
a = A()

In [36]:
a.tt 

1

In [41]:
print(A._A__x )
A.__x # 접근이 안됨.

1


AttributeError: type object 'A' has no attribute '__x'

In [52]:
class A:
    __x = 1 

    @property # decorator
    def tt(self):
        print('get')
        return A.__x # 외부에서는 __x 앞에 _A가 붙어야한다
                     # 하지만 내부에서는 접근이 된다.
    @tt.setter
    def tt(self, x):
        print('set')
        A.__x = x

In [53]:
a = A()

In [54]:
a.tt

get


1

In [55]:
a.tt = 2 # '='은 setter에 들어가서 A.__x = 2로 바꿔준다.

set


In [56]:
a.tt

get


2

In [57]:
class A:
    __x = 1 

    @property # decorator
    def tt(self):
        print('get')
        return A.__x # 외부에서는 __x 앞에 _A가 붙어야한다
                     # 하지만 내부에서는 접근이 된다.
    @tt.setter
    def tt(self, x):
        print('새롭게 값 할당 불가')
        # A.__x = x

In [58]:
a = A()

In [59]:
a.tt

get


1

In [60]:
a.tt = 2 # 값이 할당 불가능하다 
         # => a.tt는 무조건 1만 된다(초기 setting 이후 절대로 값을 바꿀수 없다 > 상수)
         # property를 통해서 상수를 만들 수있다.

새롭게 값 할당 불가


In [74]:
class A:
    __x = 1 

    @property # decorator
    def tt(self):
        print('안알려줌')
    #    return A.__x # 외부에서는 __x 앞에 _A가 붙어야한다
                     # 하지만 내부에서는 접근이 된다.
    @tt.setter
    def tt(self, x):
        print('새롭게 값 할당 불가')
        # A.__x = x

In [75]:
a = A()

In [64]:
a.tt # 값을 숨기기 위해 접근제한자의 역할도 할 수 있다.

안알려줌


In [65]:
a = np.array([1,2,3])

In [68]:
dir(a.data) # contiguous: 값을 연속적으로 지정
            # readonly: 값을 할당 못한다 > 상수 (property > setters를 사용) 
            # tolist: list로 변환한다. (to___ : data 형태를 바꿔준다.)
            # a.data: 내부적인 data를 관리한다.

['__class__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'c_contiguous',
 'cast',
 'contiguous',
 'f_contiguous',
 'format',
 'hex',
 'itemsize',
 'nbytes',
 'ndim',
 'obj',
 'readonly',
 'release',
 'shape',
 'strides',
 'suboffsets',
 'tobytes',
 'tolist',
 'toreadonly']

In [70]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [73]:
ohe.fit_transform([[1,2,3]]).toarray().tolist() #spot matrix

[[1.0, 1.0, 1.0]]

In [77]:
a = np.arange(24) # python의 range와 같다

In [78]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
a = np.arange(24).reshape(2,3,4) # 1차원 데이터를 3차원으로 변환

In [81]:
a.shape # shape으로 차원 확인 > 3차원

(2, 3, 4)

In [83]:
a # (2,3,4) > (3,4) matrix가 2개

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
a = np.arange(24).reshape(3,2,4) # (3,2,4) > (2,4) matrix가 3개
                                 # 4개짜리가 2개
                                 # [ 의 갯수 > 차원의 수
                                 # 첫번째 []를 빼면 [[]]짜리 원소 => 3개
                                 # 두번째 []를 빼면 []짜리 원소 => 2개
                                 # 세번째 []를 빼면 괄호가 없는 원소 => 4개
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
a.shape

(3, 2, 4)

In [ ]:
# 데이터가 조금만 많으면 직관적으로 확인하기 힘들다.
import tensorflow as tf
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
X_train.shape 
"""
(60000, 28, 28)
"""

In [92]:
np.zeros_like(a) # like는 shape이 같은 함수를 만들어 준다
                 # factory method 분류!

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
# from: from 뒤에 있는 데이터 구조로 부터 가져온다
# as: ~로써 새로운 데이터 타입을 만듬
# to: ~로 data structure을 변환한다 (e.g. tolist, toarray,...)
import pandas as pd

pd.DataFrame.from_dit # 카멜방식으로 만들어짐 > class method
tf.data.Dataset.from_generator
np.asfarray # f: float 어레이를 만들어라
a.astype('int8') # type을 int8로 바꿔준다.

In [93]:
import pprint # pretty print: 이쁘게 출력된다.
from pprint import pprint

In [94]:
pprint(a)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])


In [95]:
# 현실에서는 element-wise로 계산하지만, 
# python의 행렬계산에서는 shape가 달라도 자동으로 처리해주는 경우가 있다.
a = np.array([[1,2,],[3,4]])
b = np.array([[2,3,],[1,3]])

In [96]:
a

array([[1, 2],
       [3, 4]])

In [97]:
b

array([[2, 3],
       [1, 3]])

In [98]:
a.__add__ # __add__는 연산자 + 계산이 가능하다

<method-wrapper '__add__' of numpy.ndarray object at 0x000001C1F29FEC90>

In [102]:
# generic > data type에 따라 다르게 계산
from operator import add
add([1,2,], [3,4,])

[1, 2, 3, 4]

In [103]:
# 함수가 있어도 method가 없을 수 있다 (ex. a행렬은 a.__add__는 있지만, a.add는 없다. 하지만 numpy에는 add가 있다)
np.add([1,2,], [3,4,]) # ufunc = universal function
                       # ufunc이라 generic의 list +의 개념이 아닌 element-wise로 계산된다.
                       # numpy형태로 만들었기 때문에 계산이 빠르다

array([4, 6])

In [107]:
a.__sub__(a) # 내부적으로는 a - a가 실행된다.

array([[0, 0],
       [0, 0]])

In [110]:
np.subtract(a,a) # ufuc

array([[0, 0],
       [0, 0]])

In [ ]:
# 마찬가지로 tensorflow에서도 사용가능하다.
x = tf.constant([[1,2,],[3,4]])
tf.add(x,x)
"""
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>
"""

In [114]:
# 주의해야할 연산의 법칙
# shape에 따라서 연산 방법이 다를 수 있다.
a = np.array([1,2,3])
b = np.array([1,2,3])

In [116]:
a*b # elementwise calculation

array([1, 4, 9])

In [121]:
# method로 클래스 확인
a.__class__

numpy.ndarray

In [120]:
# 함수로 클래스 확인
type(a)

numpy.ndarray

In [118]:
# method에 대응하는 function은 이름이 꼭 같을 필요는 없다.
# => 확인해봐야한다. (map 같이 함수형 프로그래밍은 함수를 요구하므로 함수를 찾아야함)
np.multiply(a,b) 

array([1, 4, 9])

In [122]:
a@b # inner product, np.dot(a,b)과 같다

14

In [124]:
a.dot(b)

14

In [130]:
aa = np.array([[1,2,], [4,5,]])
bb = np.array([[1,2,], [4,5,]])

In [131]:
aa*bb

array([[ 1,  4],
       [16, 25]])

In [132]:
aa @ bb # 2차원 이상에서는 matrix product: 행렬 곱 
        # => aa, bb의 shape가 mxn, nxa처럼 각 첫번째 행렬의 열과 두번째 행렬의 행의 개수가 다르면 계산이 안된다.

array([[ 9, 12],
       [24, 33]])

In [147]:
# indexing, slicing in numpy
# 5가지
x = np.arange(120).reshape(20,6)
x

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

In [153]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [154]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [157]:
# ex. 7이 잘못됐다. 수정해야함
pprint(x) # original
pprint(x[1]) # original > first row
pprint(x[1][1]) # original > first row > element

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])
array([ 6,  7,  8,  9, 10, 11])
7


In [159]:
# 이렇게 특정 데이터를 수정하는 것 = indexing(python 방식)
x[1][1] = 100
x

array([[  0,   1,   2,   3,   4,   5],
       [  6, 100,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

In [162]:
x[1,1] = 7 # ,를 사용하면 괄호를 많이 사용하지 않고 사용할 수 있다.
x          # numpy에서만 지원하는 indexing 방법 1. comma indexing

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

In [167]:
x[(0,1), (3,1)] # 3[0,3]과 7[1,1]을 뽑고 싶다 > [(행,행) (렬,렬)] 앞에는 행, 뒤에는 열을 적어 준다.


array([3, 7])

In [171]:
x[[0,1], [3,1]] = 100 # 괄호() 대신 대괄호()를 사용하면 조금 더 보기 쉽다.
                # 2. nested indexing이라고 한다.
                # nested indexing은 차원이 한개 떨어진다.

In [172]:
# 3. advanced(fancy) indexing
x[[2,1]] # row를 뽑아온다.

array([[ 12,  13,  14,  15,  16,  17],
       [  6, 100,   8,   9,  10,  11]])

In [173]:
x[[1,2,3]] # fancy indexing은 기존 행렬의 차원을 유지시킨다.
           # 또한 순서를 바꿔서 새로운 형식에 data를 뽑는다.

array([[  6, 100,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [176]:
iris[['sepal_width', 'petal_length']], iris[['petal_length', 'sepal_width']]

(     sepal_width  petal_length
 0            3.5           1.4
 1            3.0           1.4
 2            3.2           1.3
 3            3.1           1.5
 4            3.6           1.4
 ..           ...           ...
 145          3.0           5.2
 146          2.5           5.0
 147          3.0           5.2
 148          3.4           5.4
 149          3.0           5.1
 
 [150 rows x 2 columns],
      petal_length  sepal_width
 0             1.4          3.5
 1             1.4          3.0
 2             1.3          3.2
 3             1.5          3.1
 4             1.4          3.6
 ..            ...          ...
 145           5.2          3.0
 146           5.0          2.5
 147           5.2          3.0
 148           5.4          3.4
 149           5.1          3.0
 
 [150 rows x 2 columns])

In [177]:
# 4. boolean indexing: 조건에 맞는 값을 뽑아낸다.
x[x > 40] # list(filter(lambda x:x>3, [1,2,3,4,5,6]))

array([100, 100,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [178]:
# broadcasting
# 연산하기 위해서는 모양(shape)이 맞아야한다.
a = np.array([1,2,3,4])
bb = np.array([1,2,3,])

In [179]:
a+ bb

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [180]:
# broadcast는 rule에 의해서 shape을 맞춰준다.
# => 모양을 안맞춰도 쉽게 계산할 수 있다.
# 1. 상수에 대한 연산
print(a)
a + 1 # a + [1,1,1,1] 로 맞춰줌

[1 2 3 4]


array([2, 3, 4, 5])

In [181]:
a > 2 # [1,2,3,4] > [2,2,2,2] = [False, False, True, True]

array([False, False,  True,  True])

In [182]:
# 2. 차원이 같을 때 연산 
xx = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [183]:
yy = np.array([[1,2,3]])

In [184]:
xx.shape, yy.shape

((3, 3), (1, 3))

In [186]:
xx + yy # (1,3) 행렬을 복사해서 (3,3)으로 만들어서 더해줌
        # 가로로 복사
        # [[1,2,3], [4,5,6], [7,8,9]] + [[1,2,3], [1,2,3], [1,2,3]]

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [190]:
zz = np.array([[1],[2],[3]])
zz

array([[1],
       [2],
       [3]])

In [188]:
xx.shape, zz.shape # (3,1) 행렬을 복사해서 (3,3)으로 만들어서 더해줌
                   # 세로로 복사

((3, 3), (3, 1))

In [189]:
xx + zz # [[1,2,3], [4,5,6], [7,8,9]] + [[1,1,1], [2,2,2], [3,3,3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [198]:
# broadcasting
iris['petal_width'], iris['petal_width'] + 1

(0      0.2
 1      0.2
 2      0.2
 3      0.2
 4      0.2
       ... 
 145    2.3
 146    1.9
 147    2.0
 148    2.3
 149    1.8
 Name: petal_width, Length: 150, dtype: float64,
 0      1.2
 1      1.2
 2      1.2
 3      1.2
 4      1.2
       ... 
 145    3.3
 146    2.9
 147    3.0
 148    3.3
 149    2.8
 Name: petal_width, Length: 150, dtype: float64)

In [206]:
# slicing
# numpy에서는 indexing과 slicing을 함께 사용할 수 있다.
x[2:5, 1:4] # [행, 열] slicing은 차원을 그대로 유지한다.

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [207]:
x[:, 1:4] # :만 단독으로 쓰면 전체

array([[  1,   2, 100],
       [100,   8,   9],
       [ 13,  14,  15],
       [ 19,  20,  21],
       [ 25,  26,  27],
       [ 31,  32,  33],
       [ 37,  38,  39],
       [ 43,  44,  45],
       [ 49,  50,  51],
       [ 55,  56,  57],
       [ 61,  62,  63],
       [ 67,  68,  69],
       [ 73,  74,  75],
       [ 79,  80,  81],
       [ 85,  86,  87],
       [ 91,  92,  93],
       [ 97,  98,  99],
       [103, 104, 105],
       [109, 110, 111],
       [115, 116, 117]])

In [208]:
x is x[:,:] # 생긴건 같은데 완전 같은게 아니다.

False

In [209]:
c = [1,2,3]

In [210]:
d = c

In [212]:
d[0] = 100

In [213]:
c # mutable 데이터는 바뀐다!

[100, 2, 3]

In [214]:
c = [1,2,3]
d = c
d[0] = 100

In [215]:
e = [1,2,3]
f = e[:] # 내부적으로 copy를 해준다

In [216]:
f[0] = 100
e # e != e[:]

[1, 2, 3]

In [219]:
# copy의 종류
# 2차원 이상에서는 copy를 잘 사용해야하다.
# shallow / deep copy (얕은 복사/ 깊은 복사)
cc = [[1,2], [3,4]]
dd = cc # 메모리를 공유함.
dd[0][0] = 100

In [220]:
cc # mutable은 copy하지 않기 때문에 값이 바뀐다.

[[100, 2], [3, 4]]

In [223]:
# python에서 shallow copy는 기존값이 바뀐다.
cc = [[1,2], [3,4]]
dd = cc[:] # shallow copy (dd = cc.copy()), 같은 것을 복사함.
dd[0][0] = 100
# numpy에서 copy는 deep copy이고, python에서는 shallow copy다.

In [228]:
# python에서 deep copy는 라이브러리를 불러와야한다.
import copy
cc = [[1,2], [3,4]]
dd = copy.deepcopy(cc) # deep copy
dd[0][0] = 100
cc

[[1, 2], [3, 4]]

In [230]:
... # 하나의 값을 가지는 값/ 값은 대문자로 출력된다 => object

Ellipsis

In [231]:
type(...) # 클래스는 소문자로 출력된다 => class

ellipsis

In [ ]:
# 내일해야하는 것) 5. ... indexing
x[...]