In [7]:
# compile: 최적화해서 실행시켜줌

import array

In [10]:
x =array.array('b', [1,2,3]) # 'b': signed integer
                             # homo sequence data type

In [11]:
dir(x) # sequence Data type이다.

['__add__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'buffer_info',
 'byteswap',
 'count',
 'extend',
 'frombytes',
 'fromfile',
 'fromlist',
 'fromunicode',
 'index',
 'insert',
 'itemsize',
 'pop',
 'remove',
 'reverse',
 'tobytes',
 'tofile',
 'tolist',
 'tounicode',
 'typecode']

In [13]:
print(x + x)
print(3 * x)

array('b', [1, 2, 3, 1, 2, 3])
array('b', [1, 2, 3, 1, 2, 3, 1, 2, 3])


In [14]:
import numpy as np

In [19]:
x = np.array([1,2,3.])

In [20]:
x # homo로 데이터 양식을 맞춰준다. 
  # 수체계가 커지면 큰 집합으로 양식을 맞춰준다.

array([1., 2., 3.])

In [ ]:
# 결과 값에 numpy = array로 나오는 이유는 numpy를 감싸기 때문이다 (composition)
import tensorflow as tf

xx = tf.constant([1,2,3.])
xx

"""
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 ....
"""

In [ ]:
import torch
y = torch.Tensor([1,2,3.])
y + y
"""
tensor([2., 4., 6.])
['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 ...
"""

In [42]:
# 파이썬의 array는 수학적 컨샙을 가지지 않는다
# 하지만, numpy는 수학에 사용할 수 있게 array를 만들었다.
# 하드웨어 성능을 최적화하는 것을 vectorization이라 한다.

a = [1,2,3,4,5]
b = [4,5,6,7,8]

%timeit [x*y for x,y in zip(a,b)]

379 ns ± 2.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
from operator import mul

%timeit [i for i in map(mul,[1,2,3,4,5],[4,5,6,7,8])]

356 ns ± 9.37 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [43]:
# ndarray는 연속된 메모리 공간에 할당시킨다. > 데이터를 뽑을 때 좋다 > c의 pointer
# numpy는 vector, matrix, tensor를 계산하기 쉽게 하기위해서 사용한다.
# 각 원소끼리 연산한다고 해서 element-wise라고 한다 > vectorization 가능
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
%timeit a*b

282 ns ± 1.46 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [44]:
a = np.array([1,2,3])

In [45]:
a

array([1, 2, 3])

In [48]:
b = array.array('b', [1,2,3]) # 파이썬의 array는 항상 첫번째에 data type을 표기한다.

In [47]:
print(a) # print를 했더니 array가 사라진다.

[1 2 3]


In [50]:
print(b) # 파이썬의 array를 print하면 array를 반환한다.

array('b', [1, 2, 3])


In [56]:
dir(np.array) # np.array는 __repr__를 가지고 있다.

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [52]:
# 왜 같은 array인데 다르게 반환하는가?
# repr: representation, str의 차이
class X:
    def __repr__(self):
        return('repr')
    def __str__(self):
        return ('str') 

In [53]:
x = X() # instance 생성

In [54]:
x # 이름을 불렀을 때 나오는 것을 repr

repr

In [55]:
print(x) # print할 때 나오는 것을 str

str


In [58]:
# NumPy quickstart 
type(np.array([1,2,3])) 
# class가 ndarray이다.
# factory method: 괄호로 값을 만든다고 해서 instance 되는게 아니다.
# 사용자가 쉽게 만들기 위해서 지원한다.

numpy.ndarray

In [59]:
np.ndarray((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
type(tf.constant([1,2,3.]))
"""
tensorflow.python.framework.ops.EagerTensor
"""
tf.executing_eagerly()
"""
True << True면 eager(직관적으로 보여줌)의 형태로 만들어준다.
"""

In [61]:
# factory method의 예시
np.eye(2) # 단위행렬

array([[1., 0.],
       [0., 1.]])

In [64]:
np.zeros((2,3)) # 영행렬

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# shape: row & column
a = np.ndarray((2,3), dtype = complex)

In [70]:
np.ScalarType

(int,
 float,
 complex,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.clongdouble,
 numpy.complex128,
 numpy.float16,
 numpy.float32,
 numpy.longdouble,
 numpy.float64,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.intc,
 numpy.int64,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uintc,
 numpy.uint32,
 numpy.uint64,
 numpy.void)

In [71]:
np.sctypes #scalr type

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [72]:
np.sctypeDict # 단축표현

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

In [77]:
a = np.array([[1,2,3],[2,3,]])

C:\Users\GyeongJun\AppData\Local\Temp\ipykernel_16716\2644157820.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3],[2,3,]])


In [78]:
a # 개수가 안맞으면 list의 형태 > 행렬 X

array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [93]:
a = np.array([[1,2,3],[2,3,4]], dtype = np.int16) # 'i2': 단축표현도 가능

In [94]:
a

array([[1, 2, 3],
       [2, 3, 4]], dtype=int16)

In [96]:
a.shape # 행렬 모양 확인

(2, 3)

In [97]:
a.dtype # data type 파악

dtype('int16')

In [98]:
a.size # 원소의 개수

6

In [99]:
a.ndim # 차원을 알려면

2

In [100]:
a.itemsize # 1bit = 8byte

2